wdos/forms/user.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField,BooleanField,RadioField,HiddenField,SelectField,TextField
from wtforms.validators import DataRequired,Length

class CaseForm(FlaskForm):
    case_number = StringField('案号',validators = ([DataRequired()]),render_kw = {})
    case_cause  = StringField('案由',validators = ([DataRequired()]),render_kw = {})
    case_subject_matter = StringField('标的',validators = ([DataRequired()]),render_kw = {})
    case_start_time = StringField('立案时间',render_kw = {})
    original_case_number = StringField('原审案号',render_kw = {})
    judgement_content = TextField('判决内容/执行目的',render_kw = {})
    judgement_time = StringField('判决时间',render_kw = {})
    case_end_cause = StringField('结案原因',render_kw = {})
    case_end_time = StringField('结案时间',render_kw = {})

    submit = SubmitField('保存')

class UserForm(FlaskForm):
    pass
    
class ClientForm(FlaskForm):
    client_c_d = SelectField(
            label = '案件类型',
            validators = ([DataRequired('申请人还是被执行人要分清')]),
            render_kw = {},
            choices  = [('申请人','申请人'),('被执行人','被执行人')],
            default  = '申请人'
            )
    client_name = StringField('名字',validators = ([DataRequired('要个当事人名字')]),render_kw = {})
    client_sex  = SelectField(
            label = '性别',
            validators = ([DataRequired('请选择性别')]),
            render_kw = {},
            choices = [('男','男'),('女','女')],
            default = '男'

            )
    client_ymd  = StringField('出生日期',validators = ([DataRequired()]),render_kw = {})
    client_address  = StringField('住址',validators = ([DataRequired()]),render_kw = {})
    client_id  = StringField('身份证号',render_kw = {})
    client_phone_number  = StringField('手机号码',render_kw = {})

    submit = SubmitField('保存')

class DocumentsForm(FlaskForm):
    pass
class CreateDocumentsForm(FlaskForm):
    pass

    #choice = RadioField(' ',choices = [('value1','前期'),('value2',' 后期'),('value3','自选')])
    zxtzs = BooleanField('执行通知书')
    lzjdk = BooleanField('廉政监督卡')
    qlywgzs = BooleanField('权利义务告知书')

    submit = SubmitField('开始生成')
    


class test_document(FlaskForm):
    zxtzs = BooleanField('执行通知书',render_kw = {'id': 'zx'})
    hid = HiddenField('hide',render_kw = { 'id': '隐藏'})
    submit = SubmitField('submit')

wdos/blueprints/user.py
from flask import Blueprint,render_template,flash,redirect,url_for,send_file,make_response,request
from wtforms import BooleanField,SubmitField
from flask_wtf import FlaskForm
from flask_login import login_required,current_user

from wdos.extensions import mongo,bootstrap
from wdos.forms.user import CaseForm,ClientForm,DocumentsForm,CreateDocumentsForm
from wdos.utils import is_banjiao,str_client,ishan,c_d_list
from io import BytesIO
from docxtpl import DocxTemplate

user_bp = Blueprint('user',__name__)
@user_bp.before_request
@login_required
def login_protect():
    pass

#案件相关名称清单
@user_bp.context_processor
def name_list():
    name_dict = {
            'name_list':{
                'case_number':'案号',
                'case_cause':'案由',
                'case_subject_matter':'标的',
                'case_start_time':'立案时间' ,
                'original_case_number':'原审案号' ,
                'judgement_content':'判决内容/执行目的' ,
                'judgement_time':'判决时间' ,
                'case_end_cause':'结案原因/执行过程' ,
                'case_end_time':'结案时间' ,
                
                'client_sex':'性别',
                'client_c_d':'申请人/被执行人',
                'client_name':'名字',
                'client_address':'住址',
                'client_id':'公民身份证号码',
                'client_phone_number':'当事人手机号码'
                }

            }

    return name_dict  


@user_bp.route('/new_case',methods = ['GET','POST'])
def new_case():
    form = CaseForm()
    if form.validate_on_submit():
        case_number =form.case_number.data
        case_cause = form.case_cause.data
        case_subject_matter= form.case_subject_matter.data
        case_start_time = form.case_start_time.data
        original_case_number = form.original_case_number.data
        judgement_content = form.judgement_content.data
        judgement_time = form.judgement_time.data
        case_end_cause = form.case_end_cause.data
        case_end_time = form.case_end_time.data
        case_id = str(hash(case_number + case_start_time))
        case_number = is_banjiao(case_number)

        mydict = {
                'case_id':case_id,
                'case_number':case_number,
                'case_cause':case_cause,
                'case_subject_matter':case_subject_matter,
                'case_start_time':case_start_time ,
                'original_case_number':original_case_number ,
                'judgement_content':judgement_content ,
                'judgement_time':judgement_time ,
                'case_end_cause':case_end_cause ,
                'case_end_time':case_end_time ,
                'clients':[]
                }

        in_db = mongo.db.case.find({'$or':[{'case_number':case_number},{'case_id':case_id}]}).count()

        if in_db == 0:
            x = mongo.db.case.insert_one(mydict)
            flash('案件信息提交成功'+ str(in_db))
            find = mongo.db.case.find_one({'case_id':case_id},{'_id':0,'case_id':0})
            return render_template('/user/case_details.html',find = find ,case_id = case_id)
        else:
            flash(in_db,'warning')
            return render_template('/user/index.html',form = form )

    return render_template('/user/index.html',form = form )


@user_bp.route('/')
@login_required
def case():
    find  = mongo.db.case.find({},{'_id':0})
    return render_template('user/case.html',find = find)
          

#下载文件
@user_bp.route('/downloads/<document_name>',methods = ['GET'])
def downloads(document_name):
    docxs = mongo.db.new_document.find_one({'filename':document_name})

    if docxs:
        docx = BytesIO(docxs['context'])
        filename = docxs['filename']

        return send_file(docx,as_attachment = True ,attachment_filename = filename)
    else:
        return "no case" + document_name


#详情
@user_bp.route('/case_details/<case_id>' ,methods=['GET','POST'])
def case_details(case_id):
    find = mongo.db.case.find_one({'case_id':case_id} ,{'_id':0,'case_id':0,'complaints':0,'defendants':0})
    find_docxs = mongo.db.new_document.find({'case_id':case_id})
    if find_docxs:
        all_docxs = [docx['filename'] for docx in find_docxs]
        return render_template('/user/case_details.html',find = find ,case_id = case_id,all_docxs = all_docxs)
    else:
        filename = None

#生成文书并存入new_document
@user_bp.route('/creat_documents/<case_id>',methods = ['POST','GET'])
def creat_documents(case_id):
    class DocumentsForm(FlaskForm):
        pass
    tems = mongo.db.templates.find()
    for tem in tems:
        setattr(DocumentsForm,tem['filename'],BooleanField(tem['filename']))
    setattr(DocumentsForm,'开始生成',SubmitField('开始生成'))

    form = DocumentsForm()
    if form.validate_on_submit():

        find = mongo.db.case.find_one({'case_id':case_id},{'_id':0} )
        user_detail = mongo.db.users.find_one({'user_id':current_user.id})

        clients_detail = find
        clients_detail['complaints'] = str_client(find['complaints'])
        clients_detail['defendants'] = str_client(find['defendants'])
        clients_detail['complaints_detail'] =[] 
        clients_detail['defendants_detail'] = [] 
        clients_detail['case_start_TIME']  = find['case_start_time']
        clients_detail['case_end_TIME']  = find['case_end_time']

        clients_detail['judge_name'] = user_detail['judge_name']
        clients_detail['user_phone_number'] = user_detail['user_phone_number']
        if user_detail['clerk'] != '':
            clients_detail['clerk'] = user_detail['clerk']
        if user_detail['judge_friend0'] != '':
            clients_detail['judge_friend0'] = user_detail['judge_friend0']
        if user_detail['judge_friend1'] != '':
            clients_detail['judge_friend1'] = user_detail['judge_friend1']

        for client in find['clients']:
            c =( client['client_sex'] + ',' 
            + client['client_ymd'] + ','
            + client['client_address'] +','
            + '公民身份证号码:' + client['client_id'] + '.')
            if client['client_c_d'] == '申请人':
                strc = '申请人:' + client['client_name'] + ',' + c
                clients_detail['complaints_detail'].append(strc)
            else:
                strc = '被执行人:' + client['client_name'] + ',' + c
                clients_detail['defendants_detail'].append(strc)

        mes  = request.form 

        for k,v in mes.items():
            if v:
                data = mongo.db.templates.find_one({'filename':k})
                if data:
                    tem_stream = BytesIO(data['context'])

                    doc = DocxTemplate(tem_stream)
                    doc.render(clients_detail)

                    target_stream = BytesIO()

                    doc.save(target_stream)
                    filename = find['case_number'] + k
                    n = mongo.db.new_document.find({'filename':filename}).count()
                    if n == 0:
                        mongo.db.new_document.insert({'case_id':case_id ,'filename':filename,'context':target_stream.getvalue()})
                    else:
                        mongo.db.new_document.update({'filename':filename},{'$set':{'case_id':case_id ,'filename':filename,'context':target_stream.getvalue()}})

                    tem_stream.close()
                    target_stream.close()

        flash('文书已全部生成','success')
        return  redirect(url_for('user.case_details',case_id = case_id ))

    return render_template('/user/creat_documents.html',case_id = case_id,form = form )

@user_bp.route('/edit/<case_id>',methods = ['POST','GET'])
def case_edit(case_id):
    form = CaseForm()
    find = mongo.db.case.find_one({'case_id':case_id} )

    if form.validate_on_submit():
        case_number = form.case_number.data 
        case_cause = form.case_cause.data
        case_subject_matter = form.case_subject_matter.data 
        case_start_time = form.case_start_time.data 
        original_case_number = form.original_case_number.data 
        judgement_content = form.judgement_content.data 
        judgement_time = form.judgement_time.data 
        case_end_cause = form.case_end_cause.data
        case_end_time = form.case_end_time.data 

        mydict = {
                'case_id':case_id,
                'case_number':case_number,
                'case_cause':case_cause,
                'case_subject_matter':case_subject_matter,
                'case_start_time':case_start_time ,
                'original_case_number':original_case_number ,
                'judgement_content':judgement_content ,
                'judgement_time':judgement_time ,
                'case_end_cause':case_end_cause ,
                'case_end_time':case_end_time ,
                }
        old_dict = {'case_id':case_id}
        mongo.db.case.update_one(old_dict,{ "$set":mydict})
        flash('案件信息编辑成功','success')
        return redirect(url_for('user.case_details',case_id = case_id))

    form.case_number.data =find['case_number']
    form.case_cause.data =find['case_cause']
    form.case_subject_matter.data =find['case_subject_matter']
    form.case_start_time.data =find['case_start_time']
    form.original_case_number.data =find['original_case_number']
    form.judgement_content.data =find['judgement_content']
    form.judgement_time.data =find['judgement_time']
    form.case_end_cause.data =find['case_end_cause']
    form.case_end_time.data =find['case_end_time']

    return render_template('user/case_edit.html',form  = form,case_id = case_id,find = find)

#查找案件
@user_bp.route('/search')
def search():
    q = request.args.get('q','').replace(' ','')
    if ishan(q) :
        regex = '.*' + q  + '.*'
        find = mongo.db.case.find( { '$or' : [{ '原告' : {'$regex':regex} },{ '被告': {'$regex':regex}  } ,{ '案号' : { '$regex' : regex } }  ] } )
    else:
        #regex = '.*[\(|\（]201[0-9][\)|\）]陕0823执11.*'
        regex = '.*'
        for c in q:
            if c == "(" or c =="（":
                c = '[\(|\（]'
            if c == ")" or c =="）":
                c = '[\)|\）]'

wdos/templates/user/_nav.html
<nav class="navbar bg-light navbar-light">
  <!-- Links -->
  <ul class="navbar-nav">
	<li class="nav-item">
			<a class="nav-link" href="{{ url_for('user.case_details',case_id = case_id)}}"><small>{{ find['case_number'] }}</small</a>
	</li>
	<li class="nav-item">
			<a class="nav-link" href="{{ url_for('user.case_edit',case_id =  case_id ) }}">编辑案件</a>
	</li>
	<li class="nav-item">
			<a class="nav-link" href="{{ url_for('user.creat_documents',case_id = case_id )}}">生成文书</a>
	</li>
	<li class="nav-item">
	  	<a class="nav-link" href="#">Link 3</a>
	</li>
  </ul>
 
</nav>

wdos/templates/user/add_client.html
{% extends 'user/case_tem.html'%}
{% from 'bootstrap/form.html' import render_form %}

{% block title%}添加当事人{% endblock%}
{% block case_content%}

    <div class="card w-100 bg-light">
        <h3 class="card-header">添加当事人</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
				{#	

				{{ form.csrf_token}}

				{{ form.clients.label}} 
				{{ form.clients()}}
				{{ form.client_name.label}}
				{{ form.client_name()}}

				{{ form.client_name.label }}
				{{ form.client_name() }}
				{{ form.client_sex.label  }}
				{{ form.client_sex()  }}
				{{ form.client_ymd.label  }}
				{{ form.client_ymd()  }}
				{{ form.client_address.label  }}
				{{ form.client_address()}}  
				{{ form.client_id.label  }}
				{{ form.client_id()  }}
				{{ form.client_phone_number.label  }}
				{{ form.client_phone_number()  }}
				#}

{% endblock %}

wdos/templates/user/case.html
{% extends 'base.html'%}

{% block title %}
案件
{% endblock %}

{% block content %}

<div class="page-header">
		<h2>案件列表{{ name_list['case_cause']}}
        <small class="text-muted"></small>
        <span class="float-right"><a class="btn btn-primary btn-sm"
									 href="{{ url_for('user.new_case')}}">新案件</a></span>
    </h2>
</div>
<table class="table table-striped  table-hover table-condensed ">
  <thead>
    <tr>
      <th>案号</th>
      <th>申请人/原告</th>
      <th>被执行人/被告</th>
      <th>案由</th>
      <th>立案时间</th>
    </tr>
  </thead>
  <tbody>
		  {% for f in find %}
			<tr>
					<td><a class  = "nav-link " href = "{{url_for('user.case_details',case_id = f['case_id'])}}" >{{ f['case_number'] }}</a></td>
					<td>
					{% for s in f['complaints']%}
					{{ s }}
					{% endfor %}
					</td>

					<td>
					{% for s in f['defendants']%}
					{{ s }}
					{% endfor %}
					</td>
					<td>{{ f['case_cause'] }}</td>
					<td>{{ f['case_start_time'] }}</td>
			</tr>
		{% endfor %}

  </tbody>
</table>

<ul class="pagination">
  <li class="page-item"><a class="page-link" href="#">Previous</a></li>
  <li class="page-item"><a class="page-link" href="#">1</a></li>
  <li class="page-item"><a class="page-link" href="#">2</a></li>
  <li class="page-item"><a class="page-link" href="#">3</a></li>
  <li class="page-item"><a class="page-link" href="#">Next</a></li>
</ul>
{% endblock %}

wdos/templates/user/case_details.html
{% extends 'user/case_tem.html'%}

{% block case_content %}
{#<div class = 'row'>
	<div class = 'col-md-2'>
		{% include 'user/_nav.html'%}
	</div>
<div class = 'col'>
#}
<table class="table table-striped  table-hover table-condensed ">
  <thead>
			<div class="card w-100 bg-light"><h3 class = 'card-header'>{{ find['case_number'] }}</h3></div>

  </thead>
  <tbody>
					{% for k,v in find.items() %}
					{% if k !='clients'%}
					{{ continue}}
			<tr>
					<td>{{ name_list[k] }}</td>
					<td>{{ v }}</td>

			</tr>
			{% endif%}
			{% endfor %}
    </tr>
  </tbody>

</table>
<table class="table table-striped  table-hover table-condensed ">
		<thead>
				<tr>
						<th>{{ name_list['client_c_d']}}</th>
						<th>{{ name_list['client_name']}}</th>
						<th>{{ name_list['client_sex']}}</th>
						<th>{{ name_list['client_ymd']}}</th>
						<th>{{ name_list['client_address']}}</th>
						<th>{{ name_list['client_id']}}</th>
						<th>{{ name_list['client_phone_number']}}</th>
						<th>操作</th>

				</tr>
		</thead>
		<tbody>
				{% for dic in find['clients']%}
				<tr>
						<td>{{ dic['client_c_d']}}</td>
						<td>{{ dic['client_name']}}</td>
						<td>{{ dic['client_sex']}}</td>
						<td>{{ dic['client_ymd']}}</td>
						<td>{{ dic['client_address']}}</td>
						<td>{{ dic['client_id']}}</td>
						<td>{{ dic['client_phone_number']}}</td>
				<td>
				<a class="btn btn-info btn-sm" href="{{ url_for('user.edit_client',case_id = case_id,client_name = dic['client_name'])}}">修改</a>
				<form class="inline" method="get"
					  action="{{ url_for('user.delete_client', case_id=case_id, client_name = dic['client_name']) }}">
					<button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?');">删除
					</button>
				</form>
				</td>
				</tr>

				{% endfor%}

		</tbody>
</table>
</table>
<table class="table table-striped  table-hover table-condensed ">
		<thead>
				<tr>
						<th>已生成文书</th>
				</tr>
		</thead>
		<tbody>
				{% for docx in  all_docxs %}
				<tr><td><a class = 'nav-link' href ='{{ url_for('user.downloads' ,document_name  = docx ) }}'>{{ docx }}</a></td></tr>
				{% endfor %}

		</tbody>
</table>

{% endblock %}


</div>

wdos/templates/user/case_edit.html
{% extends 'user/case_tem.html'%}
{% from 'bootstrap/form.html' import render_form %}

{% block title%} 信息修改{% endblock %}
{% block case_content %}
    <div class="card w-100 bg-light">
        <h3 class="card-header">信息修改</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>

{% endblock %}

wdos/templates/user/case_tem.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/nav.html' import render_nav_item %}

{% block content %}
    <div class="page-header">
        <h1>案件详情</h1>
    </div>
    <div class="row">
        <div class="col-md-2">
            <div class="nav  flex-column" role="tablist" aria-orientation="vertical">
                {{ render_nav_item('user.case_details', '案件详情',case_id = case_id) }}
                {{ render_nav_item('user.case_edit', '编辑案件信息',case_id = case_id) }}
				{{ render_nav_item('user.add_client', '添加当事人',case_id = case_id) }}
				{{ render_nav_item('user.creat_documents', '自动生成文书',case_id = case_id) }}
			</div>
		</div>
		<div class="col-md-10">
				{% block case_content %}{% endblock %}
		</div>
	</div>
	{% endblock %}

wdos/templates/user/creat_documents.html
{% extends "user/case_tem.html"%}
{% from 'bootstrap/form.html' import render_form %}
{% block title%}自动生成{% endblock%}
{% block case_content %}

    <div class="card w-100 bg-light">
        <h3 class="card-header">可自动生成文书</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

wdos/templates/user/edit_client.html
{% extends 'user/case_tem.html'%}
{% from 'bootstrap/form.html' import render_form %}


{% block case_content%}
    <div class="card w-100 bg-light">
        <h3 class="card-header">编辑当事人信息</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

wdos/templates/user/index.html
{% extends 'base.html'%}

{% from 'bootstrap/form.html' import render_form %}

<h1>案件详情</h1>
{% for message in get_flashed_messages() %}
{{ message }}
{% endfor %}
{% block content %}

<div class = "container col-md-4">
		<form method = "post">
		{{ render_form(form) }}
		</form>

</div>



{% endblock %}

wdos/templates/user/search.html
{% extends 'base.html'%}

{% block title %}
查找结果
{% endblock title %}
{% block content %}

<div class="page-header">
    <h2>查找结果
    </h2>
</div>

{% if find != []%}

<table class="table table-striped  table-hover table-condensed ">
  <thead>
    <tr>
      <th>案号</th>
      <th>申请人/原告</th>
      <th>被执行人/被告</th>
      <th>案由</th>
      <th>立案时间</th>
    </tr>
  </thead>
  <tbody>
		{% for f in find %}
			<tr>
					<td><a class  = "nav-link " href = "{{url_for('user.case_details',case_id = f['case_id'] )}}" >{{ f['case_number']}}</a></td>
					<td>{% for s in f['complaints']%}
					{{s}}
					{% endfor %}</td>

					<td>{% for s in f['defendants']%}
					{{s}}
					{% endfor %}</td>

					<td>{{ f['case_cause']}}</td>
					<td>{{ f['case_start_time']}}</td>
			</tr>
		{% endfor %}
    </tr>
  </tbody>
</table>
{% else%}
<div>
        <small class="text-muted"></small>
        <span class="float-lift"><a class="btn btn-primary btn-sm"
									 href="{{ url_for('user.case')}}">返回案件列表</a></span>
        <span class="float-right"><a class="btn btn-primary btn-sm"
									 href="{{ url_for('user.new_case')}}">新立案件</a></span>
</div>
{% endif %}
{% endblock content %}

wdos/templates/user/user.html
{% extends 'base.html'%}

{% block content10 %}
<h1>{{name}}</h1>
{% endblock %}