wdos/blueprints/admin.py
import time
from flask import Blueprint,render_template,url_for,flash,request,redirect
from werkzeug import secure_filename
from io import BytesIO

from wdos.extensions import mongo,User
from wdos.decorators import admin_required, permission_required
from wdos.forms.admin import LoginForm,TemplatesDocument,RegisterForm

from flask_login import login_user,login_required,logout_user,current_user
from flask_login import LoginManager

admin_bp = Blueprint('admin',__name__)

@admin_bp.route('/logout')
@login_required
def admin_logout():
    flash('工作辛苦了，再见'+current_user.username,'info')
    logout_user()
    return redirect(url_for('.admin_login'))


@admin_bp.route('/',methods = ['GET','POST'])
def admin_login():
    if current_user.is_authenticated:
        return redirect(url_for('user.case'))
    form = LoginForm()

    if form.validate_on_submit():

        username = form.username.data
        password = form.password.data

        user_one = mongo.db.users.find_one({'username':username})

        if user_one !=None and password == user_one['password']:
            user = User()
            user.id = user_one['user_id']
            user.username = user_one['judge_name']
            login_user(user)

            flash('登录成功！欢迎'+user.username,'info')
            return redirect(url_for('user.case'))
        else:
            flash('用户名或密码不对！！','warning')

            return redirect(url_for('.admin_login'))
    return render_template('admin/login.html',form = form  )

@admin_bp.route('/uploads/',methods = ['GET','POST'])
@login_required
@admin_required
def admin_uploads():
    form  = TemplatesDocument()
    templates_all = mongo.db.templates.find({},{'context':0})
    if form.validate_on_submit():
        for f in request.files.getlist('templates'):
            filename = f.filename
            
            template_stream = BytesIO()
            f.save(template_stream)
            mongo.db.templates.insert({'filename':filename,'context':template_stream.getvalue()})
            template_stream.close()

        flash('模板上传完成!','success')

    return  render_template('admin/uploads.html',form = form,templates_all = templates_all)

@admin_bp.route('/settings')
@login_required
@admin_required
def admin_settings(filename):
    pass

@admin_bp.route('/admin')
@login_required
@admin_required
def admin_case():
    find  = mongo.db.case.find({},{'_id':0})
    return render_template('admin/admin_case.html',find = find )


@admin_bp.route('/delete/<filename>',methods = ['GET','POST'])
@login_required
@admin_required
def admin_delete(filename):
    delete_file = {'filename':filename}
    mongo.db.templates.delete_one(delete_file)
    flash(filename+ "delete success",'success')
    return redirect(url_for('.admin_uploads')) 

@admin_bp.route('/register',methods = ['GET','POST'])
@login_required
@admin_required
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        court_name = form.court_name.data
        department = form.department.data
        username = form.username.data
        password = form.password.data
        re_password = form.re_password.data
        judge_name = form.judge_name.data
        judge_friend0 = form.judge_friend0.data
        judge_friend1 = form.judge_friend1.data
        clerk = form.clerk.data
        user_phone_number = form.user_phone_number.data
        register_time = time.time()
        user_id = str(hash(str(register_time) + username))
        permission = []
        user_dict = {
            'court_name'         : court_name ,
            'department'         : department ,
            'username'           : username ,
            'password'           : password ,
            're_password'        : re_password ,
            'judge_name'         : judge_name ,
            'judge_friend0'      : judge_friend0 ,
            'judge_friend1'      : judge_friend1 ,
            'clerk'              : clerk ,
            'user_phone_number'  : user_phone_number,
            'register_time'      : register_time,
            'user_id'            : user_id ,
            'permission'         : permission 

            }
        x = mongo.db.users.insert(user_dict)
        flash('chenggon' ,'sucess')
        return 'sucess' 
    return render_template('/admin/register.html',form = form)

wdos/blueprints/user.py
from flask import Blueprint,render_template,flash,redirect,url_for,send_file,make_response,request
from wtforms import BooleanField,SubmitField
from flask_wtf import FlaskForm
from flask_login import login_required,current_user

from wdos.extensions import mongo,bootstrap
from wdos.forms.user import CaseForm,ClientForm,DocumentsForm,CreateDocumentsForm
from wdos.utils import is_banjiao,str_client,ishan,c_d_list
from io import BytesIO
from docxtpl import DocxTemplate

user_bp = Blueprint('user',__name__)
@user_bp.before_request
@login_required
def login_protect():
    pass

#案件相关名称清单
@user_bp.context_processor
def name_list():
    name_dict = {
            'name_list':{
                'case_number':'案号',
                'case_cause':'案由',
                'case_subject_matter':'标的',
                'case_start_time':'立案时间' ,
                'original_case_number':'原审案号' ,
                'judgement_content':'判决内容/执行目的' ,
                'judgement_time':'判决时间' ,
                'case_end_cause':'结案原因/执行过程' ,
                'case_end_time':'结案时间' ,
                
                'client_sex':'性别',
                'client_c_d':'申请人/被执行人',
                'client_name':'名字',
                'client_address':'住址',
                'client_id':'公民身份证号码',
                'client_phone_number':'当事人手机号码'
                }

            }

    return name_dict  


@user_bp.route('/new_case',methods = ['GET','POST'])
def new_case():
    form = CaseForm()
    if form.validate_on_submit():
        case_number =form.case_number.data
        case_cause = form.case_cause.data
        case_subject_matter= form.case_subject_matter.data
        case_start_time = form.case_start_time.data
        original_case_number = form.original_case_number.data
        judgement_content = form.judgement_content.data
        judgement_time = form.judgement_time.data
        case_end_cause = form.case_end_cause.data
        case_end_time = form.case_end_time.data
        case_id = str(hash(case_number + case_start_time))
        case_number = is_banjiao(case_number)

        mydict = {
                'case_id':case_id,
                'case_number':case_number,
                'case_cause':case_cause,
                'case_subject_matter':case_subject_matter,
                'case_start_time':case_start_time ,
                'original_case_number':original_case_number ,
                'judgement_content':judgement_content ,
                'judgement_time':judgement_time ,
                'case_end_cause':case_end_cause ,
                'case_end_time':case_end_time ,
                'clients':[]
                }

        in_db = mongo.db.case.find({'$or':[{'case_number':case_number},{'case_id':case_id}]}).count()

        if in_db == 0:
            x = mongo.db.case.insert_one(mydict)
            flash('案件信息提交成功'+ str(in_db))
            find = mongo.db.case.find_one({'case_id':case_id},{'_id':0,'case_id':0})
            return render_template('/user/case_details.html',find = find ,case_id = case_id)
        else:
            flash(in_db,'warning')
            return render_template('/user/index.html',form = form )

    return render_template('/user/index.html',form = form )


@user_bp.route('/')
@login_required
def case():
    find  = mongo.db.case.find({},{'_id':0})
    return render_template('user/case.html',find = find)
          

#下载文件
@user_bp.route('/downloads/<document_name>',methods = ['GET'])
def downloads(document_name):
    docxs = mongo.db.new_document.find_one({'filename':document_name})

    if docxs:
        docx = BytesIO(docxs['context'])
        filename = docxs['filename']

        return send_file(docx,as_attachment = True ,attachment_filename = filename)
    else:
        return "no case" + document_name


#详情
@user_bp.route('/case_details/<case_id>' ,methods=['GET','POST'])
def case_details(case_id):
    find = mongo.db.case.find_one({'case_id':case_id} ,{'_id':0,'case_id':0,'complaints':0,'defendants':0})
    find_docxs = mongo.db.new_document.find({'case_id':case_id})
    if find_docxs:
        all_docxs = [docx['filename'] for docx in find_docxs]
        return render_template('/user/case_details.html',find = find ,case_id = case_id,all_docxs = all_docxs)
    else:
        filename = None

#生成文书并存入new_document
@user_bp.route('/creat_documents/<case_id>',methods = ['POST','GET'])
def creat_documents(case_id):
    class DocumentsForm(FlaskForm):
        pass
    tems = mongo.db.templates.find()
    for tem in tems:
        setattr(DocumentsForm,tem['filename'],BooleanField(tem['filename']))
    setattr(DocumentsForm,'开始生成',SubmitField('开始生成'))

    form = DocumentsForm()
    if form.validate_on_submit():

        find = mongo.db.case.find_one({'case_id':case_id},{'_id':0} )
        user_detail = mongo.db.users.find_one({'user_id':current_user.id})

        clients_detail = find
        clients_detail['complaints'] = str_client(find['complaints'])
        clients_detail['defendants'] = str_client(find['defendants'])
        clients_detail['complaints_detail'] =[] 
        clients_detail['defendants_detail'] = [] 
        clients_detail['case_start_TIME']  = find['case_start_time']
        clients_detail['case_end_TIME']  = find['case_end_time']

        clients_detail['judge_name'] = user_detail['judge_name']
        clients_detail['user_phone_number'] = user_detail['user_phone_number']
        if user_detail['clerk'] != '':
            clients_detail['clerk'] = user_detail['clerk']
        if user_detail['judge_friend0'] != '':
            clients_detail['judge_friend0'] = user_detail['judge_friend0']
        if user_detail['judge_friend1'] != '':
            clients_detail['judge_friend1'] = user_detail['judge_friend1']

        for client in find['clients']:
            c =( client['client_sex'] + ',' 
            + client['client_ymd'] + ','
            + client['client_address'] +','
            + '公民身份证号码:' + client['client_id'] + '.')
            if client['client_c_d'] == '申请人':
                strc = '申请人:' + client['client_name'] + ',' + c
                clients_detail['complaints_detail'].append(strc)
            else:
                strc = '被执行人:' + client['client_name'] + ',' + c
                clients_detail['defendants_detail'].append(strc)

        mes  = request.form 

        for k,v in mes.items():
            if v:
                data = mongo.db.templates.find_one({'filename':k})
                if data:
                    tem_stream = BytesIO(data['context'])

                    doc = DocxTemplate(tem_stream)
                    doc.render(clients_detail)

                    target_stream = BytesIO()

                    doc.save(target_stream)
                    filename = find['case_number'] + k
                    n = mongo.db.new_document.find({'filename':filename}).count()
                    if n == 0:
                        mongo.db.new_document.insert({'case_id':case_id ,'filename':filename,'context':target_stream.getvalue()})
                    else:
                        mongo.db.new_document.update({'filename':filename},{'$set':{'case_id':case_id ,'filename':filename,'context':target_stream.getvalue()}})

                    tem_stream.close()
                    target_stream.close()

        flash('文书已全部生成','success')
        return  redirect(url_for('user.case_details',case_id = case_id ))

    return render_template('/user/creat_documents.html',case_id = case_id,form = form )

@user_bp.route('/edit/<case_id>',methods = ['POST','GET'])
def case_edit(case_id):
    form = CaseForm()
    find = mongo.db.case.find_one({'case_id':case_id} )

    if form.validate_on_submit():
        case_number = form.case_number.data 
        case_cause = form.case_cause.data
        case_subject_matter = form.case_subject_matter.data 
        case_start_time = form.case_start_time.data 
        original_case_number = form.original_case_number.data 
        judgement_content = form.judgement_content.data 
        judgement_time = form.judgement_time.data 
        case_end_cause = form.case_end_cause.data
        case_end_time = form.case_end_time.data 

        mydict = {
                'case_id':case_id,
                'case_number':case_number,
                'case_cause':case_cause,
                'case_subject_matter':case_subject_matter,
                'case_start_time':case_start_time ,
                'original_case_number':original_case_number ,
                'judgement_content':judgement_content ,
                'judgement_time':judgement_time ,
                'case_end_cause':case_end_cause ,
                'case_end_time':case_end_time ,
                }
        old_dict = {'case_id':case_id}
        mongo.db.case.update_one(old_dict,{ "$set":mydict})
        flash('案件信息编辑成功','success')
        return redirect(url_for('user.case_details',case_id = case_id))

    form.case_number.data =find['case_number']
    form.case_cause.data =find['case_cause']
    form.case_subject_matter.data =find['case_subject_matter']
    form.case_start_time.data =find['case_start_time']
    form.original_case_number.data =find['original_case_number']
    form.judgement_content.data =find['judgement_content']
    form.judgement_time.data =find['judgement_time']
    form.case_end_cause.data =find['case_end_cause']
    form.case_end_time.data =find['case_end_time']

    return render_template('user/case_edit.html',form  = form,case_id = case_id,find = find)

#查找案件
@user_bp.route('/search')
def search():
    q = request.args.get('q','').replace(' ','')
    if ishan(q) :
        regex = '.*' + q  + '.*'
        find = mongo.db.case.find( { '$or' : [{ '原告' : {'$regex':regex} },{ '被告': {'$regex':regex}  } ,{ '案号' : { '$regex' : regex } }  ] } )
    else:
        #regex = '.*[\(|\（]201[0-9][\)|\）]陕0823执11.*'
        regex = '.*'
        for c in q:
            if c == "(" or c =="（":
                c = '[\(|\（]'
            if c == ")" or c =="）":
                c = '[\)|\）]'

wdos/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	{% block head%}

	<title> {% block title %}文书自动生成系统{% endblock %} </title>


	{% block styles%}
			<!-- 新 Bootstrap 核心 CSS 文件 -->
			<link href="{{ url_for('static',filename = 'css/bootstrap.min.css') }}" rel="stylesheet" type ="text/css">
			<link href="{{ url_for('static',filename = 'css/style.css') }}" rel="stylesheet" type ="text/css">

			<link rel="stylesheet" href="{{ url_for('static', filename='open-iconic/font/css/open-iconic-bootstrap.css') }}">
			<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
			<script src="{{ url_for('static',filename = 'jquery-3.4.1/jquery-3.4.1.min.js')}}"></script>
			<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
			<script src="{{ url_for('static',filename = 'js/bootstrap.min.js')}}"></script>
			<title>文书自动生成系统</title>
	{% endblock  styles%}

  </style>
	{% endblock head%}
</head>
<body>

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarColor01">
                <div class="navbar-nav mr-auto">
                    {{ render_nav_item('user.case', '所有案件') }}
					<form class="form-inline my-2 my-lg-0" action = "{{ url_for('user.search')}}">
                        <input type="text" name="q" class="form-control mr-sm-1" placeholder="案号或当事人"
                               required>
                        <button class="btn btn-light my-2 my-sm-0" type="submit">
                            <span class="oi oi-magnifying-glass"></span>
                        </button>
                    </form>
                </div>

                <div class="navbar-nav ml-auto">
								{% if current_user.is_admin() %}		
									<a class="nav-item nav-link" href="{{ url_for('admin.admin_uploads') }}" title="Upload">
										<span class="oi oi-cloud-upload"></span>&nbsp;&nbsp;
									</a>
									<a class="nav-item nav-link" href="{{ url_for('admin.register') }}" title="register">
										<span class="oi oi-list-rich "></span>&nbsp;&nbsp;
									</a>
								{% endif %}
                    <div class="dropdown nav-item">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">
                             <span class="caret">{{ current_user.username}}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" role="menu">
                            <a class="dropdown-item" href="{{ url_for('admin.admin_settings', username=current_user.username) }}">
                                <span class="oi oi-person"></span>settings
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('admin.admin_logout') }}">
                                <span class="oi oi-power-standby"></span> Logout
                            </a>
                        </div>
                    </div>
            </div>
        </div>
    </nav>
{% endblock %}

<main class="container" >
		{% for message in get_flashed_messages(with_categories = True)%}
		<div class = "alert alert-{{ message[0]}}" role = 'alert'>
			<button type = "button" class = "close" data-dismiss = "alert">&times;</button>
			{{ message[1]}}
			</div>

		{% endfor %}


	{% block content %}
	主页

	{% endblock content %}
 
	{%  block footer%}
            <footer>
                <p class="float-right">
                    <small>&copy; 2019
                        <a href="#" title="Written by Honorl ">Honorl</a> -
                        <a href="#" title="Fork me on GitHub">关于</a> -
                        <a href="" title="poo project">Processing of Documents</a>
                    </small>
				<small> - Capture and Intelligent Processing of Documents</small>
                </p>
            </footer>

	{% endblock%}

		</main>
{% block scripts %}
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
{% endblock %}
</body>
</html>

wdos/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- 新 Bootstrap 核心 CSS 文件 -->
	<link href="../static/css/bootstrap.min.css" rel="stylesheet" media="screen">
	<!-- 可选的Bootstrap主题文件（一般不用引入） -->
	<link href="../static/css/bootstrap.theme.min.css" rel="stylesheet" media="screen">
	<title>Title</title>
	<style>
  .fakeimg {
        height: 200px;
        background: #aaa;
    }
  </style>
</head>
<body>	
		<h1>	{{ test }}</h1>

		
<div class="container">
  <h2>提示框</h2>
	<p>提示框可以使用 .alert 类, 后面加上指定特定意义的颜色类来实现:</p>
	<div class="alert alert-success">
		<strong>成功!</strong> 指定操作成功提示信息。
		  </div>
		  <div class="alert alert-info">
			  <strong>信息!</strong> 请注意这个信息。
				</div>
				<div class="alert alert-warning">
					<strong>警告!</strong> 设置警告信息。
					  </div>
					  <div class="alert alert-danger">
						  <strong>错误!</strong> 失败的操作
							</div>
							<div class="alert alert-primary">
    <strong>首选!</strong> 这是一个重要的操作信息。
  </div>
  <div class="alert alert-secondary">
		      <strong>次要的!</strong> 显示一些不重要的信息。
			</div>
			<div class="alert alert-dark">
					    <strong>深灰色!</strong> 深灰色提示框。
					  </div>
					  <div class="alert alert-success">
							      <strong>浅灰色!</strong>浅灰色提示框。
								</div>
</div>

<div class="jumbotron text-center" style="margin-bottom:0">
  <h1>我的第一个 Bootstrap 4 页面</h1>
	<p>重置浏览器窗口大小查看效果！</p> 
</div>

<nav class="navbar navbar-expand-sm bg-success navbar-dark">
		<a class="navbar-brand" href="#">导航</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
				<span class="navbar-toggler-icon"></span>
				  </button>
				  <div class="collapse navbar-collapse" id="collapsibleNavbar">
						  <ul class="navbar-nav">
								  <li class="nav-item">
										  <a class="nav-link" href="#">链接</a>
												</li>
												<li class="nav-item">
														<a class="nav-link" href="#">链接</a>
															  </li>
															  <li class="nav-item">
																	  <a class="nav-link" href="#">链接</a>
																			</li>    
																				</ul>
																				  </div>  
</nav>

<div class="container" style="margin-top:30px">
		<div class="row">
				<div class="col-sm-4">
					  <h2>关于我</h2>
							<h5>我的照片:</h5>
							<div class="fakeimg">这边插入图像</div>
								  <p>关于我的介绍..</p>
										<h3>一些链接</h3>
											  <p>说明文本</p>
											  <ul class="nav nav-pills flex-column">
													  <li class="nav-item">
															  <a class="nav-link active" href="#">激活状态</a>
																	  </li>
																	  <li class="nav-item">
																			  <a class="nav-link" href="#">链接</a>
																					  </li>
																					  <li class="nav-item">
																							  <a class="nav-link" href="#">链接</a>
																									  </li>
																									  <li class="nav-item">
																											  <a class="nav-link disabled" href="#">禁用</a>
																													  </li>
																															</ul>
																															<hr class="d-sm-none">
																																</div>
																																<div class="col-sm-8">
																																	  <h2>标题</h2>
																																			<h5>副标题</h5>
																																			<div class="fakeimg">图像</div>
																																				  <p>一些文本..</p>
																																						<p>菜鸟教程，学的不仅是技术，更是梦想！！！菜鸟教程，学的不仅是技术，更是梦想！！！菜鸟教程，学的不仅是技术，更是梦想！！！</p>
																																							  <br>
																																									<h2>标题</h2>
																																										  <h5>副标题</h5>
																																										  <div class="fakeimg">图像</div>
																																												<p>一些文本..</p>
																																													  <p>菜鸟教程，学的不仅是技术，更是梦想！！！菜鸟教程，学的不仅是技术，更是梦想！！！菜鸟教程，学的不仅是技术，更是梦想！！！</p>
																																														  </div>
																																															</div>
</div>

<div class="jumbotron text-center" style="margin-bottom:0">
  <p>底部内容</p>
</div>

	<!--html content-->
	
		<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
		<script src="../static/js/jquery.js"></script>
			<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
			<script src="../static/js/bootstrap.min.js"></script>
</body>
</html>